# Generated by Django 3.1.2 on 2020-10-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirrel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='The latitude of the squirrel being seen.')),
                ('longitude', models.FloatField(help_text='The longitude of the squirrel being seen.')),
                ('unique_squirrel_id', models.CharField(help_text='The unique ID of this squirrel.', max_length=50)),
                ('shift', models.CharField(choices=[('AM', 'in the morning'), ('PM', 'in the afternoon')], max_length=2)),
                ('date', models.DateField(help_text='The date that the squirrel was seen.')),
                ('age', models.CharField(blank=True, help_text='The age group of the squirrel.', max_length=8)),
            ],
        ),
    ]
