# Generated by Django 3.1.2 on 2020-10-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='age',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult squirrel'), ('Juvenile', 'Juvenile squirrel')], help_text='The age group of the squirrel.', max_length=8),
        ),
    ]
