# Generated by Django 3.1.2 on 2020-10-18 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0002_auto_20201017_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_latitude', models.FloatField()),
                ('new_longitude', models.FloatField()),
                ('new_unique_squirrel_id', models.CharField(max_length=50)),
                ('new_shift', models.CharField(choices=[('AM', 'in the morning'), ('PM', 'in the afternoon')], max_length=2)),
                ('new_date', models.DateField()),
                ('new_age', models.CharField(blank=True, choices=[('Adult', 'Adult squirrel'), ('Juvenile', 'Juvenile squirrel')], max_length=8)),
                ('squirrel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squirrel.squirrel')),
            ],
        ),
    ]
